# Using container-based infrastructure
# sudo: false
# enable trusty beta
sudo: required
dist: trusty

# 'bash' will define a generic environment without interfering environment
# settings like "CC=gcc"
language: bash

# Only build the master branch
branches:
    only:
        - master

# Caching the downloaded src packages between several builds to save travis-ci
# download time and bandwidth
cache:
    directories:
        - $HOME/src
        - $HOME/x-tools
        # - $HOME/zlib-install
        # - $HOME/openssl-install
        # - $HOME/pcre-install
        # - $HOME/libsodium-install
        # - $HOME/mbedtls-install
        # - $HOME/libev-install


# Installing needed dependencies
addons:
    apt:
        packages:
            - bison
            - flex
            - gperf
            # - libncurses5
            # - libncurses5-dev
            # - libncursesw5
            # - libncursesw5-dev
            - texinfo
            - help2man
            - asciidoc
            - xmlto
            - libgmp-dev 
            - nettle-dev
            # - libtool
            # - autogen
            # - automake
            - libstdc++6
            - lib32stdc++6 
            - net-tools
            - perl
            # - python
            
            - gcc-multilib
            - g++-multilib
            - lib32z1-dev
            # - gconf
            # - pkg-config

            - libelf1:i386
            # - libelf1-32bit
            # - uuid-dev
            # - libuuid1
            # - uuid-runtime
            - libltdl-dev
            # for miniupnpd
            # - libiptc-dev
            # - iptables-dev
            

# Handle git submodules yourself
git:
    submodules: false
    
# Use sed to replace the SSH URL with the public URL, then initialize submodules
# before_install:
    # - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    # - git submodule update --init --recursive
    # - sudo apt-get update -qq
    # - sudo apt-get install libpcre3 libpcre3-dev -y
    
# Building crosstool-NG core
# keep these on at all times because it is fast
install:
    - pwd

# Here is the list of all the standard samples tracked
# by the continuous integration system
env:
    matrix:
        # - export PATH=$HOME/x-tools/mipsel-unknown-linux-uclibc/bin:$PATH
        # - BROADCOM_SDK=6

        # - TT_BUILD=ac68e
        - TT_BUILD=ac68z
        # - TT_BUILD=n18e
        # - TT_BUILD=n18z
        # - TT_BUILD=r7000e

        # - TT_BUILD=dir868l

        # - TT_BUILD=r7000e
        - TT_BUILD=r7000z
        # - TT_BUILD=r6400e
        # - TT_BUILD=r6400z
        # - TT_BUILD=r7000init
        # - TT_BUILD=r6250init
        # - TT_BUILD=r6300v2init
        # - TT_BUILD=r6400init

        - TT_BUILD=r1do

        # - TT_BUILD=ws880e
        # - TT_BUILD=ws880z

        # - TT_BUILD=wzr1750e
        # - TT_BUILD=wzr1750z

        # - TT_BUILD=ea6700e
        # - TT_BUILD=ea6700z
    
    global:
        - secure: MU4rMTYYHd8YZChUDNcfyEnHO9v4h45oPhl5FDLnZ7mGMSyQOxWaVzEqCBXBQDTbF0kN1guF4aBydCrILDkhHk/KZ3313nQBdhyjJccxhwDcJMmZZ+tbRpquInLTEQxQyG3XZ4DRm4nQRYp69AJoaWth6uWAR+VXOL57ub19Yt/wAB6bJ6NOsbR5C6sAL7xeZ0k9UbZleHVO1lpWdFofYfEqwemQ7VHWz9xYE7hAatFgUWoGnyA8ju7R3NnsEw5cksXicyU/R7EGDdN4BRdgj/Aqy0TsitJlLl7WfkpmqLgkn8L6ad3UdojPw3mb/LOQ9q8hHMCwXOtJAV0jWXXERlQjaNNACIis590cYoE3/LtsJfYpnD5F8t6fbVyUjval0mGx9jx81EEyzi+N4AqWLGIscnuR3ZgbW+bUlgLJ5Vm5B70bt2Cs4YaPLWqNLxrojDdjyFMr8CJzsOiBASZmj3wuCWnV+hyRnwZ/Eo1a0RHkuXy+6DbqfcunLIzATo4P0xAfVHhH1XtaqCu5NXXVtsvAK3AlesAW24ozXi726RXwz3b95rYQTgf9Ho+bP7vzD+I496xHFRu/Rceko+4isAqr274meEFw1Vzz5tUslWcmkYL7r7ve3pmmxbOguy25J5C2Z/Jov/h6FR07pK3TFtK281KCGcxJgQFis8oTErE=

        - BROADCOM_SDK=src-rt-6.x.4708

# Building the standard samples
script:
    # - . ls -l $HOME
    - . $TRAVIS_BUILD_DIR/.travis.sh      # Load the travis environment
    - echo ============================
    - pre_build_prep  > /dev/null
    - build_tomato

# On failure displaying the last lines of the log file
after_failure:
    - echo ============= tomato ===============
    - tail -n 1000 ~/tomato.txt
    
    
after_success: . $TRAVIS_BUILD_DIR/update-gh-pages.sh
